// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp1_iID2X9PkXaX7xLf_FCdzdC-PY5IaI',
    appId: '1:761255731598:web:9b278dc739128cd64004df',
    messagingSenderId: '761255731598',
    projectId: 'ventaselectromax-5166e',
    authDomain: 'ventaselectromax-5166e.firebaseapp.com',
    storageBucket: 'ventaselectromax-5166e.firebasestorage.app',
    measurementId: 'G-65KSR3X7MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXr0kiVnnVCWTV37waTQ7odiT8aVzpcak',
    appId: '1:761255731598:android:1e289f8f12deecba4004df',
    messagingSenderId: '761255731598',
    projectId: 'ventaselectromax-5166e',
    storageBucket: 'ventaselectromax-5166e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp1_iID2X9PkXaX7xLf_FCdzdC-PY5IaI',
    appId: '1:761255731598:web:9c5ccc7a0ba64d7a4004df',
    messagingSenderId: '761255731598',
    projectId: 'ventaselectromax-5166e',
    authDomain: 'ventaselectromax-5166e.firebaseapp.com',
    storageBucket: 'ventaselectromax-5166e.firebasestorage.app',
    measurementId: 'G-61LHPPDEPX',
  );
}
